### ISSUE TITLE
Singularity image not found

### ISSUE THREAD

**Issue by laramaktub** [MASILab/tbi_ct_lesion_segmentation#2]
Hi!

Thanks a lot for sharing this code. I have never used singularity images, but to my understanding, there is some tbi_ct_lesion_segmentation.sif file missing.

Thanks!

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
